language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]]; then pecl install libevent; pecl install event; fi;

script:
  - phpunit --coverage-text
