language: php

php:
  #- 5.4
  #- 5.5
  - 5.6
  - 7
  #- hhvm
  #- hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    #- php: hhvm
    #- php: hhvm-nightly
  fast_finish: true

install:
  - set -e
  - set -o pipefail
  
  - sudo apt-get install -y libevent-dev
  
  - echo "yes" | pecl install event
  
  # install 'libev' PHP extension
  - git clone --recursive https://github.com/m4rw3r/php-libev
  - pushd php-libev
  - phpize
  - ./configure --with-libev
  - make
  - make install
  - popd
  - echo "extension=libev.so" >> "$(php -r 'echo php_ini_loaded_file();')"

script:
  - phpunit --coverage-text
