language: php

php:
  #- 5.4
  #- 5.5
  - 5.6
  - 7
  #- hhvm
  #- hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    #- php: hhvm
    #- php: hhvm-nightly
  fast_finish: true

install:
  - sudo apt-get install libevent-dev
  - pecl install libevent;
  - pecl install event;

script:
  - phpunit --coverage-text
